# Site settings
title: Girl Talk, Girl Code
header-img: img/home-bg.png
email: emesfun@gmail.com
copyright_name: eyosef
description: > # this means to ignore newlines until "baseurl:"
  My passage into programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eyosef
learn_profile: eyosef
email_username: emesfun@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
